!     ******   ZDAY.INC   ******
!     zero daily accumulators
      CALL ZEROA(NLAYER, VRFLDI, INFLDI, BYFLDI, DSFLDI)
      CALL ZEROA(NLAYER, NTFLDI, TRANDI, DUMM, DUMM)
      CALL ZERO(SRFLD, GWFLD, SEEPD, SLFLD, DUMMY, DUMMY)
      CALL ZERO(IRVPD, ISVPD, SLVPD, SNVPD, SFALD, PSLVPD)
      CALL ZERO(RFALD, SINTD, RINTD, RSNOD, SMLTD, DUMMY)
      CALL ZERO(MESFLD, PTRAND, PINTD, DUMMY, DUMMY, DUMMY)
