!     ******   ZMONTH.INC   ******
!     zero monthly accumulators
      CALL ZEROA(NLAYER, VRFLMI, INFLMI, BYFLMI, DSFLMI)
      CALL ZEROA(NLAYER, NTFLMI, TRANMI, DUMM, DUMM)
      CALL ZERO(SRFLM, GWFLM, SEEPM, SLFLM, DUMMY, DUMMY)
      CALL ZERO(IRVPM, ISVPM, SLVPM, SNVPM, SFALM, DUMMY)
      CALL ZERO(RFALM, SINTM, RINTM, RSNOM, SMLTM, DUMMY)
      CALL ZERO(MESFLM, PTRANM, PINTM, PSLVPM, DUMMY, DUMMY)
      AWATM=0.0d0
